/// Events generated by the UI thread and sent to the JS runtime
#[derive(Debug, Clone)]
pub enum UiEvent {
    /// Window was resized
    WindowResized { width: u32, height: u32 },

    /// Mouse click occurred
    MouseClick { x: f64, y: f64 },

    /// Mouse moved
    MouseMove { x: f64, y: f64 },

    /// Key was pressed
    KeyPress {
        key: String,
        modifiers: KeyModifiers,
    },

    /// Key was released
    KeyRelease {
        key: String,
        modifiers: KeyModifiers,
    },

    /// Text input received
    TextInput { text: String },

    /// Widget action triggered (button click, etc.)
    WidgetAction {
        widget_id: String,
        action: WidgetActionKind,
    },

    /// Window focus changed
    WindowFocusChanged { focused: bool },

    /// Window close requested
    WindowCloseRequested,

    /// Application is about to exit
    AppExit,
}

/// Keyboard modifier state
#[derive(Debug, Clone, Default)]
pub struct KeyModifiers {
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub meta: bool,
}

/// Kind of widget action
#[derive(Debug, Clone)]
pub enum WidgetActionKind {
    Click,
    DoubleClick,
    TextChanged(String),
    ValueChanged(f64),
    Custom(String),
}
